import { chromium } from 'playwright';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1600, height: 900 } });
const errs = [];
page.on('pageerror', err => errs.push('PAGEERROR: '+err.message));
page.on('console', msg => { if (msg.type() === 'error') errs.push('CONSOLE: '+msg.text()); });
await page.goto('http://localhost:3000/', { waitUntil: 'load', timeout: 30000 });
await page.waitForTimeout(9000);
await page.screenshot({ path: 'e:/project-innofusion3.0/scratch_shot/redesign3.png' });
console.log('ERR', JSON.stringify(errs, null, 2));
await browser.close();
